FROM nvcr.io/nvidia/pytorch:22.04-py3

RUN mkdir /cfs && pip install stable-baselines3 && pip install opencv-python-headless && pip install julia jill ipython --no-cache-dir && pip install Flask && pip install grequests && pip install waitress

ENV JILL_INSTALL_DIR=$HOME/.local/.julia

RUN mkdir -p $HOME/.local/.julia && jill install --confirm

# PyJulia setup (installs PyCall & other necessities)
RUN python -c "import julia; julia.install()"

# Helpful Development Packages
RUN julia -e 'using Pkg; Pkg.add(["Revise", "HDF5", "PyCall"]); pkg"precompile"'